# Melanoma Detection

In [2]:
# Imports
import os
import kagglehub
import polars as pl
import torch
import torchvision

## Preparing Data

In [3]:
# Download latest version
path = kagglehub.dataset_download("andrewmvd/isic-2019")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.8), please consider upgrading to the latest version (0.3.10).
Path to dataset files: /home/cam/.cache/kagglehub/datasets/andrewmvd/isic-2019/versions/1

In [4]:
!ls {path}

ISIC_2019_Training_GroundTruth.csv  ISIC_2019_Training_Metadata.csv
ISIC_2019_Training_Input

In [5]:
df_train_meta = pl.read_csv(os.path.join(path, "ISIC_2019_Training_Metadata.csv"))
df_train_labels = pl.read_csv(os.path.join(path, "ISIC_2019_Training_GroundTruth.csv"))
df_train_meta.head()

shape: (5, 5)
┌──────────────┬────────────┬─────────────────────┬───────────┬────────┐
│ image        ┆ age_approx ┆ anatom_site_general ┆ lesion_id ┆ sex    │
│ ---          ┆ ---        ┆ ---                 ┆ ---       ┆ ---    │
│ str          ┆ i64        ┆ str                 ┆ str       ┆ str    │
╞══════════════╪════════════╪═════════════════════╪═══════════╪════════╡
│ ISIC_0000000 ┆ 55         ┆ anterior torso      ┆ null      ┆ female │
│ ISIC_0000001 ┆ 30         ┆ anterior torso      ┆ null      ┆ female │
│ ISIC_0000002 ┆ 60         ┆ upper extremity     ┆ null      ┆ female │
│ ISIC_0000003 ┆ 30         ┆ upper extremity     ┆ null      ┆ male   │
│ ISIC_0000004 ┆ 80         ┆ posterior torso     ┆ null      ┆ male   │
└──────────────┴────────────┴─────────────────────┴───────────┴────────┘

In [7]:
df_train_labels.head()

shape: (5, 10)
┌──────────────┬─────┬─────┬─────┬───┬─────┬──────┬─────┬─────┐
│ image        ┆ MEL ┆ NV  ┆ BCC ┆ … ┆ DF  ┆ VASC ┆ SCC ┆ UNK │
│ ---          ┆ --- ┆ --- ┆ --- ┆   ┆ --- ┆ ---  ┆ --- ┆ --- │
│ str          ┆ f64 ┆ f64 ┆ f64 ┆   ┆ f64 ┆ f64  ┆ f64 ┆ f64 │
╞══════════════╪═════╪═════╪═════╪═══╪═════╪══════╪═════╪═════╡
│ ISIC_0000000 ┆ 0.0 ┆ 1.0 ┆ 0.0 ┆ … ┆ 0.0 ┆ 0.0  ┆ 0.0 ┆ 0.0 │
│ ISIC_0000001 ┆ 0.0 ┆ 1.0 ┆ 0.0 ┆ … ┆ 0.0 ┆ 0.0  ┆ 0.0 ┆ 0.0 │
│ ISIC_0000002 ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 0.0 ┆ 0.0  ┆ 0.0 ┆ 0.0 │
│ ISIC_0000003 ┆ 0.0 ┆ 1.0 ┆ 0.0 ┆ … ┆ 0.0 ┆ 0.0  ┆ 0.0 ┆ 0.0 │
│ ISIC_0000004 ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 0.0 ┆ 0.0  ┆ 0.0 ┆ 0.0 │
└──────────────┴─────┴─────┴─────┴───┴─────┴──────┴─────┴─────┘

In [ ]:
# Create folders for Pytorch Data Loader
for label in df_train_labels.columns[1:]
os.makedirs(os.path.dirname(os.path.join(path, label)), exist_ok=True)

In [16]:
train_ds = torchvision.datasets.ImageFolder(
    os.path.join(path, "ISIC_2019_Training_Input", "ISIC_2019_Training_Input"))

FileNotFoundError: Couldn't find any class folder in /home/cam/.cache/kagglehub/datasets/andrewmvd/isic-2019/versions/1/ISIC_2019_Training_Input/ISIC_2019_Training_Input.